root_dir = "_site"

# When links are available using HTTPS, treat HTTP links as errors.
require_https = true

# Exclude URLs and mail addresses from checking (supports regex).
exclude = [
  '^https://web\.archive\.org/web/',
  '^https://fonts\.gstatic\.com/',
  '^https://fonts\.googleapis\.com',
  'https://www.deviantart.com/lanotdesign/art/homeless-characters-154275235',
  'https://www.linkedin.com/in/',
  'https://www.npmjs.com/~',
]
